@echo off
setlocal

where gradle >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo Gradle was not found on PATH.
    echo Install Gradle or use the Gradle Wrapper generated by your IDE.
    exit /b 1
)

gradle %*
exit /b %ERRORLEVEL%
